-- Additional editable prompt templates (syntheses, follow-up, briefing).
ALTER TYPE "AnalysisKind" ADD VALUE IF NOT EXISTS 'FOLLOW_UP_EMAIL';
ALTER TYPE "AnalysisKind" ADD VALUE IF NOT EXISTS 'MEETING_BRIEFING';
ALTER TYPE "AnalysisKind" ADD VALUE IF NOT EXISTS 'SELLER_PERFORMANCE';
ALTER TYPE "AnalysisKind" ADD VALUE IF NOT EXISTS 'SELLER_AFFINITY';
ALTER TYPE "AnalysisKind" ADD VALUE IF NOT EXISTS 'ORG_KISS_ROLLUP';
ALTER TYPE "AnalysisKind" ADD VALUE IF NOT EXISTS 'TEAM_COACHING';
